-- DB set up MYSQL
-- Drop tables if they exist
DROP TABLE IF EXISTS `CURRENCY_CONVERSION_RATES`;
DROP TABLE IF EXISTS `CSV_FILE`;
DROP TABLE IF EXISTS `REF_CURRENCY`;

-- Create the REF_CURRENCY table
CREATE TABLE `REF_CURRENCY` (
    `REF_CURRENCY_ID` INT AUTO_INCREMENT PRIMARY KEY,
    `CURRENCY_NAME` VARCHAR(50) NOT NULL UNIQUE,
    `CURRENCY_CODE` VARCHAR(10) NOT NULL UNIQUE, 
    `CURRENCY_ALPHA_CODE` VARCHAR(10) NOT NULL UNIQUE,
    `CURRENCY_NUMERIC_CODE` VARCHAR(10) NOT NULL UNIQUE
);

-- Create the CSV_FILE table
CREATE TABLE `CSV_FILE` ( 
    `CSV_FILE_ID` INT AUTO_INCREMENT PRIMARY KEY,
    `FILE_NAME` VARCHAR(50) NOT NULL, 
    `FILE_PATH` VARCHAR(100) NOT NULL,
    `UPLOAD_TIME` DATETIME NOT NULL
);

-- Create the CURRENCY_CONVERSION_RATES table
CREATE TABLE `CURRENCY_CONVERSION_RATES` (
    `CURRENCY_CONVERSION_RATES_ID` INT AUTO_INCREMENT PRIMARY KEY,
    `CSV_FILE_ID` INT NOT NULL,
    `CURRENCY_ID_1` INT NOT NULL,
    `CURRENCY_ID_2` INT NOT NULL,
    `CONVERSION_RATE` VARCHAR(20) NOT NULL,
    `INVERSE_CONVERSION_RATE` VARCHAR(20) NOT NULL,
    `DATE` DATETIME NOT NULL,
    CONSTRAINT `FK_CCR_RC1` FOREIGN KEY (`CURRENCY_ID_1`) REFERENCES `REF_CURRENCY` (`REF_CURRENCY_ID`),
    CONSTRAINT `FK_CCR_RC2` FOREIGN KEY (`CURRENCY_ID_2`) REFERENCES `REF_CURRENCY` (`REF_CURRENCY_ID`),
    CONSTRAINT `FK_CCR_CF` FOREIGN KEY (`CSV_FILE_ID`) REFERENCES `CSV_FILE` (`CSV_FILE_ID`)
);

--- To add an index 

CREATE INDEX idx_currency_code ON REF_CURRENCY (CURRENCY_CODE);

CREATE INDEX idx_csv_file_id ON CURRENCY_CONVERSION_RATES (CSV_FILE_ID);

-- Insert values into REF_CURRENCY
INSERT INTO `REF_CURRENCY` (`CURRENCY_NAME`, `CURRENCY_CODE`, `CURRENCY_ALPHA_CODE`, `CURRENCY_NUMERIC_CODE`)
VALUES ('U.S.Dollar', 'USD', 'USD', '840'),
       ('Indian Rupee', 'INR', 'INR', '356');
	   
	
